apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-netpol
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-postgres
  policyTypes:
    - Ingress
  ingress: 
    - from:
        podSelector:
          matchLabels:
            app: {{ .Release.Name }}-app
      ports:
        - protocol: TCP
          port: {{ .Values.database.port }}
